<a href="https://colab.research.google.com/github/sebojal/Clase/blob/main/CD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# This is formatted as code
```



In [ ]:
array = list()
arreglo = []

for i in range(10):
  numero = int(input("Dime un numero: "))
  array.append(numero)
  #El append lo añade al final, mientras el array.insert lo añade en donde yo especifique
  #Se puede borrar con .remove (donde especifico) y con .pop (al final)
  arreglo.append(-1*numero)

print(array)
print(arreglo)

Dime un numero: 1
Dime un numero: 2
Dime un numero: 3
Dime un numero: 4
Dime un numero: 5
Dime un numero: 6
Dime un numero: 7
Dime un numero: 8
Dime un numero: 9
Dime un numero: 10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10]


In [ ]:
diccionario = dict()
dictionary = {}
#Es lo mismo usar dict y {}

for i in range(10):
  numero = int(input("Dime un numero: "))
  diccionario[numero] = i
  dictionary[numero] = -1*i

print(diccionario)
print(dictionary)


Dime un numero: 2
Dime un numero: 3
Dime un numero: 4
Dime un numero: 5
Dime un numero: 6
Dime un numero: 7
Dime un numero: 9
Dime un numero: 8
Dime un numero: 10
Dime un numero: 4
{2: 0, 3: 1, 4: 9, 5: 3, 6: 4, 7: 5, 9: 6, 8: 7, 10: 8}
{2: 0, 3: -1, 4: -9, 5: -3, 6: -4, 7: -5, 9: -6, 8: -7, 10: -8}


Usando Numpy

In [6]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a.shape

(3, 4)

In [14]:
a.dtype #nos da el tipo de dato del arreglo

dtype('int64')

In [12]:
#Para agarrar ciertos cachos del arreglo usamos notacion de tuplas, [inicio:fin, inicio:fin]

a[:2,1:]
a[0:3,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [15]:
b = a #shallow copy (crea un puntero b, que apunta a a)

b[2,3] = 2024 #Hacemos un cambio para mostrar el shallow copy

b

array([[   1,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11, 2024]])

In [16]:
c = np.copy(a) #Deep copy, crea un espacio de memoria para el arreglo c, y copia los datos de a en c

c

array([[   1,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11, 2024]])

In [20]:
d = np.ones((3,5))

d[2,3] = 25
d

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 25.,  1.]])

In [21]:
e = np.zeros((3,5))
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
f = np.random.randint(7,24, size = (3,5))
f

array([[20, 14, 23, 14, 15],
       [19, 15, 14, 15, 20],
       [16, 10, 23, 22, 15]])

In [28]:
f = (np.random.random(size = (3,5)))*100
f

array([[ 8.17740262, 28.96277183, 86.36205561, 36.85464913, 24.23939147],
       [81.76748901, 39.09739979, 89.96901963, 62.35547179, 81.45646661],
       [48.4659707 , 89.40013019, 80.41610097, 57.35735079,  6.90921267]])

In [30]:
#otras opciones de importar funciones de numpy
from numpy import asarray
from numpy import savetxt

np.savetxt("ejemplo.txt", f, delimiter= ",") #se guarda el arreglo como un archivo csv


Para cargar archivos csv (como de excel), los drageamos a la parte de files.