<a href="https://colab.research.google.com/github/sebojal/Clase/blob/main/Tarea5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Abriendo el archivo csv y guardandolo en el arreglo
matrix = np.genfromtxt("/content/datos_olas.csv" ,delimiter = ',', skip_header=1 ,usecols = 2)
matrix.shape = (25,4)
print(matrix) #Muestra la matriz, cada columna representa un punto del parque

[[4.87846407 0.32100211 9.66505196 2.06802943]
 [8.64743269 1.06894673 5.77223335 5.43816497]
 [3.38164145 8.76214502 6.96088407 7.88082663]
 [6.33768938 3.58551699 8.04451408 9.15816324]
 [2.13039671 7.61968527 5.00819467 6.37610633]
 [8.9881659  1.70137878 1.96649351 4.67404529]
 [4.52179454 0.36118524 9.30103056 0.8744858 ]
 [3.85608113 9.34172845 2.94161329 4.10572062]
 [2.38798363 1.50692247 3.72435097 0.89682111]
 [7.24512516 9.8232728  2.92417257 1.26318852]
 [6.71030984 0.15471541 0.34886137 4.04010562]
 [9.97729349 3.26750884 1.65166459 8.273038  ]
 [1.92433762 8.63080405 6.37591022 8.28376454]
 [2.53633869 7.12911371 1.7874111  0.58673902]
 [2.59805142 4.02955131 5.98578425 4.0273011 ]
 [8.64441421 9.87457455 4.34168313 1.81043761]
 [9.41294896 0.33557212 7.96428109 5.29567959]
 [6.03024126 9.41816043 3.19682152 1.42667961]
 [7.02214669 9.33762327 3.67891574 2.95519895]
 [0.03941384 7.65294224 5.02642205 8.72841157]
 [9.64399382 3.32370131 7.40063791 1.12339274]
 [9.14553084 

In [8]:
#Calculando los promedios y guardandolos en una matriz de (1, 4)
promedios = np.mean(matrix, axis = 0)
print(promedios)
for i in range(4):
  #Imprimimos usando el codigo ASCII para hacerlo más simple
  print(f"El promedio en el punto {chr(65+i)} es:", promedios[i])

[6.01363418 5.01544974 5.00212788 4.21997325]
El promedio en el punto A es: 6.013634184431512
El promedio en el punto B es: 5.015449735938172
El promedio en el punto C es: 5.002127881286767
El promedio en el punto D es: 4.219973252747889


In [9]:
#Calculando la altura máxima en cada punto:
alturas_max = np.max(matrix, axis = 0)
print(alturas_max)
for i in range(4):
  print(f"La altura máxima en el punto {chr(65+i)} es:", alturas_max[i])

[9.97729349 9.87457455 9.66505196 9.15816324]
La altura máxima en el punto A es: 9.977293486806257
La altura máxima en el punto B es: 9.874574551710007
La altura máxima en el punto C es: 9.665051956287837
La altura máxima en el punto D es: 9.15816323638438


In [10]:
#Calculando la desviacion estandar en cada punto
desviaciones_estandar = np.std(matrix, axis = 0)
print(desviaciones_estandar)
for i in range(4):
  print(f"La desviacion estandar en el punto {chr(65+i)} es:", desviaciones_estandar[i])

[2.90341844 3.52685106 2.63462491 2.92687097]
La desviacion estandar en el punto A es: 2.903418443995361
La desviacion estandar en el punto B es: 3.5268510593015523
La desviacion estandar en el punto C es: 2.6346249141939784
La desviacion estandar en el punto D es: 2.9268709653745444


In [11]:
#Encontrar el punto del parque con la altura promedio más alta y mostrar su promedio
punto_max = np.argmax(promedios)
print(f"El punto con la altura promedio más alta es: {chr(65+punto_max)}")

El punto con la altura promedio más alta es: A


In [19]:
#Encontrando el dia con la altura maxima observada
altura_max = np.max(matrix)
#Encontrando el indice
index_max = np.where(matrix == altura_max)
print(f"El dia con la altura maxima observada es: {index_max[0][0]} y la altura máxima correspondiente es: {altura_max}")

El dia con la altura maxima observada es: 11 y la altura máxima correspondiente es: 9.977293486806257


In [20]:
#Guardando los resultados en un arreglo
resultados = np.array([promedios, alturas_max, desviaciones_estandar])
print(resultados)
np.savetxt('resultados_olas.txt', resultados, delimiter=',', fmt='%.2f', header='Promedios', comments='')


[[6.01363418 5.01544974 5.00212788 4.21997325]
 [9.97729349 9.87457455 9.66505196 9.15816324]
 [2.90341844 3.52685106 2.63462491 2.92687097]]
